---
  # tasks file for ansible-nifi with Hortonworks DataFlow (HDF) packages
- name: download HDF YUM .repo file to /etc/yum.repos.d
  get_url:
    url: "{{ hdf_yum_repo_file }}"
    dest: /etc/yum.repos.d
    mode: 0644
    checksum: sha256:{{ hdf_yum_repo_file_checksum }}
  when: ansible_os_family == "RedHat" and hortonworks|bool
  tags: [install,hortonworks]

- name: install HDF packages via YUM
  yum: name=nifi state=present
  when: ansible_os_family == "RedHat" and hortonworks|bool
  tags: [install,hortonworks]

- file: dest={{hdf_install_dir}} owner={{nifi_run_as}} group={{nifi_run_as}} recurse=yes